#!bash
export $(egrep -v '^#' ../.env | xargs)
sudo -E docker build \
    --build-arg SERVER_IDENTITY_SERVICE_PATH=$SERVER_IDENTITY_SERVICE_PATH \
    --build-arg SERVER_IDENTITY_SERVICE_HOST=$SERVER_IDENTITY_SERVICE_HOST \
    --build-arg SERVER_IDENTITY_SERVICE_PORT=$SERVER_IDENTITY_SERVICE_PORT \
    --build-arg DISCOVERY_SERVICE_PATH=$DISCOVERY_SERVICE_PATH \
    --build-arg DISCOVERY_SERVICE_HOST=$DISCOVERY_SERVICE_HOST \
    --build-arg DISCOVERY_SERVICE_PORT=$DISCOVERY_SERVICE_PORT \
    --build-arg RESOURCES_MANAGER_SERVICE_SECRET=$RESOURCES_MANAGER_SERVICE_SECRET \
    --build-arg RESOURCES_MANAGER_SERVICE_NAME=$RESOURCES_MANAGER_SERVICE_NAME \
    -t resources_manager_service .