import os


SERVICE_SECRET = os.environ['SERVICE_SECRET']
JWT_SECRET = os.environ['JWT_SECRET']
API_VERSION = 'v1'
SERVICE_NAME = 'gateway_service'

SERVER_IDENTITY_SERVICE_HOST = os.environ['SERVER_IDENTITY_SERVICE_HOST']
SERVER_IDENTITY_SERVICE_PORT = os.environ['SERVER_IDENTITY_SERVICE_PORT']
SERVER_IDENTITY_SERVICE_PATH = os.environ['SERVER_IDENTITY_SERVICE_PATH']
SERVER_IDENTITY_URL = \
    f'{SERVER_IDENTITY_SERVICE_HOST}:{SERVER_IDENTITY_SERVICE_PORT}/' \
    f'{SERVER_IDENTITY_SERVICE_PATH}'

DISCOVERY_SERVICE_HOST = os.environ['DISCOVERY_SERVICE_HOST']
DISCOVERY_SERVICE_PORT = os.environ['DISCOVERY_SERVICE_PORT']
DISCOVERY_SERVICE_PATH = os.environ['DISCOVERY_SERVICE_PATH']
DISCOVERY_URL = \
    f'{DISCOVERY_SERVICE_HOST}:{DISCOVERY_SERVICE_PORT}/' \
    f'{DISCOVERY_SERVICE_PATH}'
