import os


SERVICE_SECRET = os.environ['GATEWAY_SERVICE_SECRET']
JWT_SECRET = os.environ['GATEWAY_JWT_SECRET']
API_VERSION = 'v1'
SERVICE_NAME = os.environ['GATEWAY_SERVICE_NAME']

SERVER_IDENTITY_SERVICE_HOST = os.environ['SERVER_IDENTITY_SERVICE_HOST']
SERVER_IDENTITY_SERVICE_PORT = os.environ['SERVER_IDENTITY_SERVICE_PORT']
SERVER_IDENTITY_SERVICE_PATH = os.environ['SERVER_IDENTITY_SERVICE_PATH']
SERVER_IDENTITY_URL = \
    f'{SERVER_IDENTITY_SERVICE_HOST}:{SERVER_IDENTITY_SERVICE_PORT}/' \
    f'{SERVER_IDENTITY_SERVICE_PATH}'

DISCOVERY_SERVICE_HOST = os.environ['DISCOVERY_SERVICE_HOST']
DISCOVERY_SERVICE_PORT = os.environ['DISCOVERY_SERVICE_PORT']
DISCOVERY_SERVICE_PATH = os.environ['DISCOVERY_SERVICE_PATH']
DISCOVERY_URL = \
    f'{DISCOVERY_SERVICE_HOST}:{DISCOVERY_SERVICE_PORT}/' \
    f'{DISCOVERY_SERVICE_PATH}'
OBJECT_DETECTION_CHANNEL = os.environ['OBJECT_DETECTION_CHANNEL']
