#!bash
export $(egrep -v '^#' ../.env | xargs)
sudo -E docker build \
    --build-arg FACE_DETECTION_SERVICE_NAME=$FACE_DETECTION_SERVICE_NAME \
    --build-arg FACE_DETECTION_SERVICE_SECRET=$FACE_DETECTION_SERVICE_SECRET \
    --build-arg SERVER_IDENTITY_SERVICE_NAME=$SERVER_IDENTITY_SERVICE_NAME \
    --build-arg SERVER_IDENTITY_SERVICE_HOST=$SERVER_IDENTITY_SERVICE_HOST \
    --build-arg SERVER_IDENTITY_SERVICE_PORT=$SERVER_IDENTITY_SERVICE_PORT \
    --build-arg DISCOVERY_SERVICE_NAME=$DISCOVERY_SERVICE_NAME \
    --build-arg DISCOVERY_SERVICE_HOST=$DISCOVERY_SERVICE_HOST \
    --build-arg DISCOVERY_SERVICE_PORT=$DISCOVERY_SERVICE_PORT \
    --build-arg FACE_DETECTION_CHANNEL=$FACE_DETECTION_CHANNEL \
    --build-arg AGE_ESTIMATION_CHANNEL=$AGE_ESTIMATION_CHANNEL \
    -t face_detection_service .