#!bash
sudo -E docker build \
    --build-arg PEOPLE_DETECTION_SERVICE_NAME=$PEOPLE_DETECTION_SERVICE_NAME \
    --build-arg PEOPLE_DETECTION_SERVICE_SECRET=$PEOPLE_DETECTION_SERVICE_SECRET \
    --build-arg SERVER_IDENTITY_SERVICE_PATH=$SERVER_IDENTITY_SERVICE_PATH \
    --build-arg SERVER_IDENTITY_SERVICE_HOST=$SERVER_IDENTITY_SERVICE_HOST \
    --build-arg SERVER_IDENTITY_SERVICE_PORT=$SERVER_IDENTITY_SERVICE_PORT \
    --build-arg DISCOVERY_SERVICE_PATH=$DISCOVERY_SERVICE_PATH \
    --build-arg DISCOVERY_SERVICE_HOST=$DISCOVERY_SERVICE_HOST \
    --build-arg DISCOVERY_SERVICE_PORT=$DISCOVERY_SERVICE_PORT \
    --build-arg OBJECT_DETECTION_CHANNEL=$OBJECT_DETECTION_CHANNEL \
    --build-arg FACE_DETECTION_CHANNEL=$FACE_DETECTION_CHANNEL \
    -t people_detection_service .