import logging

VERIFY_SERVICE_IDENTITY_PATH = 'verify_service_identity'
LOCATE_SERVICES_PATH = 'locate_services'
DETECT_PEOPLE_PATH = 'detect_people'
DETECT_FACES_PATH = 'detect_faces'
ESTIMATE_AGE_PATH = 'estimate_age'

PEOPLE_DETECTION_COLOR = (0, 255, 0)
FACE_DETECTION_COLOR = (0, 0, 255)
AGE_ESTIMATION_COLOR = (255, 0, 0)

AGE_BLURRING_THRESHOLD = 23

LOGGING_LEVEL = logging.INFO
