import os

API_VERSION = 'v1'
SERVICE_NAME = os.environ['FACE_DETECTION_SERVICE_NAME']
SERVICE_SECRET = os.environ['FACE_DETECTION_SERVICE_SECRET']
SERVER_IDENTITY_SERVICE_HOST = os.environ['SERVER_IDENTITY_SERVICE_HOST']
SERVER_IDENTITY_SERVICE_PORT = os.environ['SERVER_IDENTITY_SERVICE_PORT']
SERVER_IDENTITY_SERVICE_PATH = os.environ['SERVER_IDENTITY_SERVICE_PATH']
SERVER_IDENTITY_URL = \
    f'{SERVER_IDENTITY_SERVICE_HOST}:{SERVER_IDENTITY_SERVICE_PORT}/' \
    f'{SERVER_IDENTITY_SERVICE_PATH}'
DISCOVERY_SERVICE_HOST = os.environ['DISCOVERY_SERVICE_HOST']
DISCOVERY_SERVICE_PORT = os.environ['DISCOVERY_SERVICE_PORT']
DISCOVERY_SERVICE_PATH = os.environ['DISCOVERY_SERVICE_PATH']
DISCOVERY_URL = \
    f'{DISCOVERY_SERVICE_HOST}:{DISCOVERY_SERVICE_PORT}/' \
    f'{DISCOVERY_SERVICE_PATH}'
WEIGHTS_PATH = os.path.join(
    os.path.dirname(__file__), '..', 'weights', 'weights.pth'
)
CONFIDENCE_THRESHOLD = 0.3
TOP_K_PREDICTIONS_TO_TAKE = 20
NMS_THRESHOLD = 0.4
