#!bash
export $(egrep -v '^#' ../.env | xargs)
sudo -E docker build \
    --build-arg DB_USER=$DB_USER \
    --build-arg DB_SECRET=$DB_SECRET \
    --build-arg DB_HOST=$DB_HOST \
    --build-arg USER_IDENTITY_DB_NAME=$USER_IDENTITY_DB_NAME \
    --build-arg USER_IDENTITY_SERVICE_NAME=$USER_IDENTITY_SERVICE_NAME \
    --build-arg USER_IDENTITY_SERVICE_SECRET=$USER_IDENTITY_SERVICE_SECRET \
    --build-arg ADMIN_IDENTITY_RESOURCES_JWT_SECRET=$ADMIN_IDENTITY_RESOURCES_JWT_SECRET \
    --build-arg SERVER_IDENTITY_SERVICE_PATH=$SERVER_IDENTITY_SERVICE_PATH \
    --build-arg SERVER_IDENTITY_SERVICE_HOST=$SERVER_IDENTITY_SERVICE_HOST \
    --build-arg SERVER_IDENTITY_SERVICE_PORT=$SERVER_IDENTITY_SERVICE_PORT \
    --build-arg DISCOVERY_SERVICE_PATH=$DISCOVERY_SERVICE_PATH \
    --build-arg DISCOVERY_SERVICE_HOST=$DISCOVERY_SERVICE_HOST \
    --build-arg DISCOVERY_SERVICE_PORT=$DISCOVERY_SERVICE_PORT \
    -t user_identity_service .